//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreetingCard {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.DropDownList lstBackColor;
		
		protected System.Web.UI.WebControls.DropDownList lstFontName;
		
		protected System.Web.UI.WebControls.TextBox txtFontSize;
		
		protected System.Web.UI.WebControls.RadioButtonList lstBorder;
		
		protected System.Web.UI.WebControls.CheckBox chkPicture;
		
		protected System.Web.UI.WebControls.TextBox txtGreeting;
		
		protected System.Web.UI.WebControls.Button cmdUpdate;
		
		protected System.Web.UI.WebControls.Panel pnlCard;
		
		protected System.Web.UI.WebControls.Label lblGreeting;
		
		protected System.Web.UI.WebControls.Image imgDefault;
	}
}
